#!/usr/bin/env perl
use strict;
use warnings;
use File::Temp ();
use File::Find;
use File::Path;
use Module::CoreList;

$ENV{PERL5LIB} = "./lib:$ENV{PERL5LIB}";

my ($exclude) = map { qr{$_} } join '|', qw(^Sub::Name$ ^Class::XSAccessor);

open my $trace_fh, '>', '.fat-trace.pl';
find({no_chdir => 1, wanted => sub {
    -f or return;
    s/\.pm$// or return;
    s{^lib/}{};
    s{/}{::}g;
    print { $trace_fh } "use $_ ();\n";
}}, 'lib');
close $trace_fh;

system 'fatpack', 'trace', "--to=.fat-trace.lst", '.fat-trace.pl' and die;
my @trace = do {
    open my $fh, '<', '.fat-trace.lst' or die $!;
    <$fh>;
};
chomp @trace;
@trace = grep {
    my $mod = $_;
    $mod =~ s/\.pm$//;
    $mod =~ s{/}{::}g;
    ! ( $Module::CoreList::version{5.008008}{$mod} || $mod =~ $exclude )
} @trace;

my @packlists = `fatpack packlists-for @trace`;
chomp @packlists;

rmtree('fatlib');
system 'fatpack', 'tree', @packlists and die;

my $content = "#!/usr/bin/env perl\n";
$content .= `fatpack file`;
$content .= do {
    open my $fh, '<', 'bin/bcssh' or die;
    <$fh>
};

open my $fh, '>', 'bcssh';
print { $fh } $content;
close $fh;
chmod 0777 & ~umask, 'bcssh';
print "wrote bcssh\n";

rmtree('fatlib');
unlink '.fat-trace.pl';
unlink '.fat-trace.lst';

